### ISSUE TITLE
autoToString may fail if the object resolves to any by TypeScript

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-microbit#1156]
https://makecode.microbit.org/_H49Fp8aHLf23

```
Uncaught Error: Error: cannot determine parent of FunctionDeclaration
    at userError (https://pxt.azureedge.net/blob/9f4b7dcf17a9f80ca38459650a8a23238565eddf/pxtworker.js:117251:21)
    at getEnclosingFunction (https://pxt.azureedge.net/blob/9f4b7dcf17a9f80ca38459650a8a23238565eddf/pxtworker.js:117473:21)
    at isTopLevelFunctionDecl (https://pxt.azureedge.net/blob/9f4b7dcf17a9f80ca38459650a8a23238565eddf/pxtworker.js:117505:66)
    at isOnDemandDecl (https://pxt.azureedge.net/blob/9f4b7dcf17a9f80ca38459650a8a23238565eddf/pxtworker.js:118946:53)
    at isUsed (https://pxt.azureedge.net/blob/9f4b7dcf17a9f80ca38459650a8a23238565eddf/pxtworker.js:118954:25)
    at markUsed (https://pxt.azureedge.net/blob/9f4b7dcf17a9f80ca38459650a8a23238565eddf/pxtworker.js:118979:30)
    at Object.compileBinary (https://pxt.azureedge.net/blob/9f4b7dcf17a9f80ca38459650a8a23238565eddf/pxtworker.js:118094:13)
    at Object.allDiags (https://pxt.azureedge.net/blob/9f4b7dcf17a9f80ca38459650a8a23238565eddf/pxtworker.js:123937:46)
    at Object.performOperation (https://pxt.azureedge.net/blob/9f4b7dcf17a9f80ca38459650a8a23238565eddf/pxtworker.js:124091:45)
    at onmessage (https://makecode.microbit.org/beta---worker:201:28)
    at userError (https://pxt.azureedge.net/blob/9f4b
```

**Comment by pelikhan** [comment]
![image](https://user-images.githubusercontent.com/4175913/44906904-1c6c5380-accb-11e8-9068-96b51896fc10.png)

**Comment by riknoll** [comment]
That stack trace is actually unrelated; it's being thrown because the project you shared doesn't have a file named `main.ts` so the compiler doesn't know where to start.
