### ISSUE TITLE
MakeCode beta hanged once during load

### ISSUE THREAD

**Issue by microbit-carlos** [Microsoft/pxt-microbit#1374]
**Describe the bug**
Went to the beta editor yesterday (9th October 2018) and the page hanged at the loading modal.
Looks like there might be an unhandled error, console output:

```
beta:1 Document was loaded from Application Cache with manifest https://makecode.microbit.org/beta---manifest
beta:1 Application Cache Checking event
beta:1 Application Cache NoUpdate event
beta:1 Application Cache Checking event
beta:1 Application Cache NoUpdate event
pxtapp.js:1880 Browser: chrome 69.0.3497.100 on mac
pxtapp.js:1880 enabled webusb
pxtapp.js:1880 PouchDB adapter: idb
main.js:201 Uncaught Error: trying to access outdated session
    at Object.assert (https://pxt.azureedge.net/blob/9377c721dfedbc4a61769dd1182028ad7146b823/pxtapp.js:155:27)
    at checkSession (https://pxt.azureedge.net/blob/3f102ab796124623567ec12721bdf006112b4d72/main.js:170:4074)
    at Object.getHeader (https://pxt.azureedge.net/blob/3f102ab796124623567ec12721bdf006112b4d72/main.js:170:3849)
    at https://pxt.azureedge.net/blob/3f102ab796124623567ec12721bdf006112b4d72/main.js:5:70637
    at Array.filter (<anonymous>)
    at https://pxt.azureedge.net/blob/3f102ab796124623567ec12721bdf006112b4d72/main.js:5:70600
    at c (https://pxt.azureedge.net/blob/3f102ab796124623567ec12721bdf006112b4d72/main.js:201:72960)
    at T._settlePromiseFromHandler (https://pxt.azureedge.net/blob/3f102ab796124623567ec12721bdf006112b4d72/main.js:201:46253)
    at T._settlePromise (https://pxt.azureedge.net/blob/3f102ab796124623567ec12721bdf006112b4d72/main.js:201:47053)
    at T._settlePromise0 (https://pxt.azureedge.net/blob/3f102ab796124623567ec12721bdf006112b4d72/main.js:201:47752)
    at T._settlePromises (https://pxt.azureedge.net/blob/3f102ab796124623567ec12721bdf006112b4d72/main.js:201:49079)
    at https://pxt.azureedge.net/blob/3f102ab796124623567ec12721bdf006112b4d72/main.js:201:2811
From previous event:
    at T.I [as _captureStackTrace] (https://pxt.azureedge.net/blob/3f102ab796124623567ec12721bdf006112b4d72/main.js:201:16130)
    at T._then (https://pxt.azureedge.net/blob/3f102ab796124623567ec12721bdf006112b4d72/main.js:201:41710)
    at T.then (https://pxt.azureedge.net/blob/3f102ab796124623567ec12721bdf006112b4d72/main.js:201:40066)
    at HTMLDocument.<anonymous> (https://pxt.azureedge.net/blob/3f102ab796124623567ec12721bdf006112b4d72/main.js:5:70546)
DevTools failed to parse SourceMap: https://pxt.azureedge.net/blob/dd22520c096be24e7432f5b46e8aad59711f31f0/ai.0.js.map
```

It worked again the next time I loaded https://makecode.microbit.org/beta, so it's not a permanent issue.

**To Reproduce**
1. Go to https://makecode.microbit.org/beta
2. See error

Of course, this happened within my chrome session, so not sure what needs to have happened before hand to recreate the same state.

**Expected behavior**
MakeCode to load.

**Screenshots**
![image](https://user-images.githubusercontent.com/29712657/46722304-1627aa80-cc6d-11e8-88bd-de891f73db90.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version: 69.0.3497.100 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by pelikhan** [comment]
Did you have the editor opened in multiple tabs by any chance?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by microbit-carlos** [comment]
Good catch, while I cannot confirm with certainty, that is quite possible.
At that point I had about 5 chrome windows with several tabs each, so while I'm sure that specific window did not have any MakeCode instance open, it is possible I did have one with a forgotten makecode tab in a minimised window.

**Comment by pelikhan** [comment]
Was this filling up the update reload?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by microbit-carlos** [comment]
Not sure I understood the question @pelikhan, could you elaborate a bit?

**Comment by pelikhan** [comment]
Say you have 5 tabs with MakeCode and they decide to reload with the update all at the same time. In that scenario, it could possible that you end up in situation. In any case, we should handle the error more gracefully.

**Comment by microbit-carlos** [comment]
Oh I see you mean now, thanks for the clarification.
Can't really say if any of the other MakeCode tabs were updating, but yes, that would be quite possible as well.

**Comment by abchatra** [comment]
Not seen in the wild. Closing for now.
