### ISSUE TITLE
Link behaviour erratic 

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1434]
**Describe the bug**
When sharing https://makecode.microbit.org/_54xWWzdztU0F created  in makecode.microbit.org/beta I am taken to the editor at https://makecode.microbit.org/v1#editor

This is not the case for other users who are redirected here: https://makecode.microbit.org/v1/13777-68951-86521-62206 and then redirected to a blank editor at v0

![2018-10-16 09 38 25](https://user-images.githubusercontent.com/31242877/47003989-72d10c80-d128-11e8-9cc3-789b2bc6946e.gif)

Console error
 
Document was loaded from Application Cache with manifest https://makecode.microbit.org/---manifest
/#pub:13777-68951-86521-62206:1 Application Cache Checking event
/#pub:13777-68951-86521-62206:1 Application Cache NoUpdate event
pxtlib.js:1406 Browser: chrome 69.0.3497.100 on mac
3/#pub:13777-68951-86521-62206:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22
pxtlib.js:1410 Error: math requires target version 1.1.73 (you are running 0.14.54)
    at Object.userError (https://pxt.azureedge.net/blob/82f2deb8cd8e87b77e6cd718705bd92acb0d4873/pxtlib.js:596:25)
    at MainPackage.Package.validateConfig (https://pxt.azureedge.net/blob/82f2deb8cd8e87b77e6cd718705bd92acb0d4873/pxtlib.js:1632:23)
    at MainPackage.Package.parseConfig (https://pxt.azureedge.net/blob/82f2deb8cd8e87b77e6cd718705bd92acb0d4873/pxtlib.js:1800:18)
    at https://pxt.azureedge.net/blob/82f2deb8cd8e87b77e6cd718705bd92acb0d4873/pxtlib.js:1815:75
From previous event:
    at MainPackage.Package.loadAsync (https://pxt.azureedge.net/blob/82f2deb8cd8e87b77e6cd718705bd92acb0d4873/pxtlib.js:1815:43)
    at MainPackage.installAllAsync (https://pxt.azureedge.net/blob/82f2deb8cd8e87b77e6cd718705bd92acb0d4873/pxtlib.js:1948:25)
    at https://pxt.azureedge.net/blob/0b61b6e99c1b1c0845662cc16e8e0cdd2fa33c38/main.js:8172:32
From previous event:
    at Object.loadPkgAsync (https://pxt.azureedge.net/blob/0b61b6e99c1b1c0845662cc16e8e0cdd2fa33c38/main.js:8169:10)
    at ProjectView.loadHeaderAsync (https://pxt.azureedge.net/blob/0b61b6e99c1b1c0845662cc16e8e0cdd2fa33c38/main.js:613:20)
    at loadHeaderBySharedId (https://pxt.azureedge.net/blob/0b61b6e99c1b1c0845662cc16e8e0cdd2fa33c38/main.js:1943:21)
    at handleHash (https://pxt.azureedge.net/blob/0b61b6e99c1b1c0845662cc16e8e0cdd2fa33c38/main.js:1916:13)
    at https://pxt.azureedge.net/blob/0b61b6e99c1b1c0845662cc16e8e0cdd2fa33c38/main.js:2059:25
From previous event:
    at HTMLDocument.<anonymous> (https://pxt.azureedge.net/blob/0b61b6e99c1b1c0845662cc16e8e0cdd2fa33c38/main.js:2058:10)
    at l (https://pxt.azureedge.net/blob/4d9b3a258759c53e7bc66b6fc554c51e2434437c/jquery.js:2:29375)
    at c (https://pxt.azureedge.net/blob/4d9b3a258759c53e7bc66b6fc554c51e2434437c/jquery.js:2:29677)

**To Reproduce**

**Expected behavior**
Link opens in v1 for all

**Desktop (please complete the following information):**
 - OS: mac 
 - Browser Chrome/Firefox

**Comment by abchatra** [comment]
This is basically basic.showNumber(10 ** 0.5) fails while compiling (works fine in the simulator).
