### ISSUE TITLE
sorry we couldn't recognize this file error missing in v1

### ISSUE THREAD

**Issue by microbit-mark** [Microsoft/pxt-microbit#1560]
suport ticket: 18273
**Describe the bug**
in v0 Trying to add a file produced in a different editor gives a "sorry we couldn't recognize this file" error.

![screen recording 2018-10-30 at 04 54 pm](https://user-images.githubusercontent.com/31242877/47735691-f3cdef00-dc64-11e8-92ad-400efaf6b27f.gif)

The same file drag and drop imported to v1 does not error.
![screen recording 2018-10-30 at 04 55 pm](https://user-images.githubusercontent.com/31242877/47735753-0cd6a000-dc65-11e8-9d02-5cb297b6868c.gif)

**To Reproduce**
Drag and drop attached file into v0 and v1 editors [kitronik_buggy_JW_dfu.hex.zip](https://github.com/Microsoft/pxt-microbit/files/2530691/kitronik_buggy_JW_dfu.hex.zip)

**Expected behavior**
Error message should display. Also [raised in DAL](https://github.com/lancaster-university/microbit-dal/issues/404#issuecomment-433995945) it would be great if the message was more descriptive eg "this file was created using micropython / C++"

**Desktop (please complete the following information):**
 - OS:Mac 10.14
 - Browser Firefox 63

**Comment by abchatra** [comment]
Import from v0 to v1 is not supported.

**Comment by abchatra** [comment]
Sorry I miss understood. This is from non-makecode hex to makecode v1.

**Comment by microbit-mark** [comment]
Is this something we can prioritise? It would be good to show an error if the file isn't recognised as a makecode HEX. Is there a reason we wouldn't want that?

**Comment by microbit-carlos** [comment]
For more information, dropping a non-makecode hex into the current beta shows this error in the console:

```
main.js:201 Uncaught Error: This .hex file doesn't contain source.
    at error (https://pxt.azureedge.net/blob/b286c6d8cf9eb01f223386d4460cc4851c38b762/pxtapp.js:4216:39)
    at unpackSourceFromHexAsync (https://pxt.azureedge.net/blob/b286c6d8cf9eb01f223386d4460cc4851c38b762/pxtapp.js:4235:24)
    at https://pxt.azureedge.net/blob/b286c6d8cf9eb01f223386d4460cc4851c38b762/pxtapp.js:4209:24
    at c (https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:201:72960)
    at T._settlePromiseFromHandler (https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:201:46253)
    at T._settlePromise (https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:201:47053)
    at T._settlePromise0 (https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:201:47752)
    at T._settlePromises (https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:201:49079)
    at https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:201:2811
From previous event:
    at T.I [as _captureStackTrace] (https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:201:16130)
    at T._then (https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:201:41710)
    at T.then (https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:201:40066)
    at Object.unpackSourceFromHexFileAsync (https://pxt.azureedge.net/blob/b286c6d8cf9eb01f223386d4460cc4851c38b762/pxtapp.js:4207:57)
    at t.importHexFile (https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:5:25176)
    at t.importFile (https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:5:28047)
    at https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:5:27930
    at HTMLBodyElement.<anonymous> (https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:59:797)
```




makecode.microbit.org version:  1.2.11
Microsoft MakeCode version:  4.4.7
microbit runtime version:  v2.1.0

**Comment by microbit-mark** [comment]
@abchatra you've tagged as next release. This would be a good one to fix please
