### ISSUE TITLE
Can't build PXT...

### ISSUE THREAD

**Issue by tsekino62** [Microsoft/pxt-microbit#1647]
**Describe the bug**

i cant finish build pxt.

```
[vagrant@localhost pxt]$ npm run build

> pxt-core@5.0.6 build /vagrant/pxt
> jake

[built/web/main.js] cd .; node node_modules/browserify/bin/cmd built/webapp/src/app.js -o built/web/main.js
Error: Cannot find module 'pouchdb/extras/memory' from '/vagrant/pxt/built/webapp/src'
    at /vagrant/pxt/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/vagrant/pxt/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/vagrant/pxt/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/vagrant/pxt/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/vagrant/pxt/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /vagrant/pxt/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
jake aborted.
TypeError: task.fail is not a function
    at ChildProcess.ch.on (/vagrant/pxt/jakeutil.js:110:18)
    at emitTwo (events.js:126:13)
(See full trace by running task with --trace)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pxt-core@5.0.6 build: `jake`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pxt-core@5.0.6 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-11-16T16_37_01_093Z-debug.log
```

this is debug.log.
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle pxt-core@5.0.6~prebuild: pxt-core@5.0.6
6 info lifecycle pxt-core@5.0.6~build: pxt-core@5.0.6
7 verbose lifecycle pxt-core@5.0.6~build: unsafe-perm in lifecycle true
8 verbose lifecycle pxt-core@5.0.6~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/vagrant/pxt/node_modules/.bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/vagrant/.local/bin:/home/vagrant/bin
9 verbose lifecycle pxt-core@5.0.6~build: CWD: /vagrant/pxt
10 silly lifecycle pxt-core@5.0.6~build: Args: [ '-c', 'jake' ]
11 silly lifecycle pxt-core@5.0.6~build: Returned: code: 1  signal: null
12 info lifecycle pxt-core@5.0.6~build: Failed to exec build script
13 verbose stack Error: pxt-core@5.0.6 build: `jake`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid pxt-core@5.0.6
15 verbose cwd /vagrant/pxt
16 verbose Linux 3.10.0-862.14.4.el7.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error pxt-core@5.0.6 build: `jake`
22 error Exit status 1
23 error Failed at the pxt-core@5.0.6 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**To Reproduce**

1.  git clone https://github.com/microsoft/pxt
1. cd pxt
1. npm i -f
1. npm run buid

**Desktop (please complete the following information):**

- OS: Windows8

On Vitrualbox

 - OS: CentOS7

Vagrantfile
```
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provision "shell", inline: <<-SHELL
      curl -sL https://rpm.nodesource.com/setup_8.x | sudo bash -
      yum install -y git nodejs vim
  SHELL
end
```

Thanks in advance.

**Comment by tsekino62** [comment]
Sorry, i can build it.
thunks.
