### ISSUE TITLE
Hex file fails to open with neopixel version error; creates unusable project

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [Microsoft/pxt-microbit#1724]
Support request: 18761

**Describe the bug**
[This hex file](https://github.com/Microsoft/pxt-microbit/files/2662553/microbit-RC-car-1.txt) fails to open in MakeCode.

The UI shows "Oops, something went wrong when importing your project".

The dev tools console shows the following trace:

```
pxtapp.js:1734 Error: version not specified for neopixel
    at Object.userError (https://pxt.azureedge.net/blob/b286c6d8cf9eb01f223386d4460cc4851c38b762/pxtapp.js:384:25)
    at Package.resolveVersionAsync (https://pxt.azureedge.net/blob/b286c6d8cf9eb01f223386d4460cc4851c38b762/pxtapp.js:7996:23)
    at Package.downloadAsync (https://pxt.azureedge.net/blob/b286c6d8cf9eb01f223386d4460cc4851c38b762/pxtapp.js:8003:25)
    at https://pxt.azureedge.net/blob/b286c6d8cf9eb01f223386d4460cc4851c38b762/pxtapp.js:8253:75
    at c (https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:201:72960)
    at T._settlePromiseFromHandler (https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:201:46253)
    at T._settlePromise (https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:201:47053)
    at T._settlePromiseCtx (https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:201:47559)
    at https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:201:2692
From previous event:
    at T.I [as _captureStackTrace] (https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:201:16130)
    at T._then (https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:201:41710)
    at T.done (https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:201:40135)
    at t.importHexFile (https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:5:25208)
    at t.importFile (https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:5:28047)
    at https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:5:27930
    at HTMLBodyElement.<anonymous> (https://pxt.azureedge.net/blob/1288c9d92177f811452cdb75a709f41454f5e073/main.js:59:797)
```

Although unsuccessful, the import does add a project to the user's "My Projects" list on the home page.

Attempting to open this project hangs forever while showing the loading modal, with a similar trace on the console. The user raising the support request wanted to remove this project, but this does not seem possible. If we're able to tell that import has failed completely then I think we should avoid adding the project or clean it up.

**Comment by abchatra** [comment]
@riknoll can you take a peek? Looks like neopixel upgrade issue.

**Comment by riknoll** [comment]
Here's the `pxt.json` for that project:

```json
{
    "name": "RC-car-1",
    "dependencies": {
        "neopixel": "*",
        "core": "*",
        "radio": "*"
    },
    "description": "",
    "files": [
        "main.blocks",
        "main.ts"
    ]
}
```

The neopixel entry should look something like this:

```
"neopixel": "github:microsoft/pxt-neopixel#v0.6.10"
```

but we also shouldn't crash

**Comment by abchatra** [comment]
Ok lower priority then. We will have script manager soon in Microbit to clean up stale projects.

**Comment by riknoll** [comment]
Fixed by https://github.com/Microsoft/pxt/pull/5330
