### ISSUE TITLE
[pxt.json:1.3.1] see many error in chrome console in today's beta portal

### ISSUE THREAD

**Issue by xuefengedu** [Microsoft/pxt-microbit#1868]
**Describe the bug**
[pxt.json:1.3.1] see many error in chrome console in today's beta portal

**To Reproduce**
1. Go to https://makecode.microbit.org/beta#editor
2. The page is always loading and see below error in chrome console

```
Document was loaded from Application Cache with manifest https://makecode.microbit.org/beta---manifest
beta#editor:1 Application Cache Checking event
pxtapp.js:1828 Browser: chrome 68.0.3440.106 on windows
beta#editor:1 Application Cache NoUpdate event
pxtapp.js:1828 PouchDB adapter: idb
psopafpj:1 Failed to load resource: the server responded with a status of 404 ()
main.js:663 Database has a global failure DOMException
guardedConsole @ main.js:663
pxtapp.js:1832 n
pxt.reportException @ pxtapp.js:1832
pxtapp.js:1828 table: set failed, cleaning translation db
pxtapp.js:1832 DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at openTransactionSafely (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:45271)
    at https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:47350
    at https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:48484
    at i (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:40024)
    at https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:40145
    at Array.forEach (<anonymous>)
    at preprocessAttachments (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:40031)
    at idbBulkDocs (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:47277)
    at PouchDB.e._bulkDocs (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:53087)
    at PouchDB.<anonymous> (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:31706)
    at PouchDB.<anonymous> (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:2836)
    at PouchDB.<anonymous> (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:206:135)
    at https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:2177
    at T.e._execute (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:15596)
    at T._resolveFromExecutor (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:45852)
From previous event:
    at T.I [as _captureStackTrace] (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:16130)
    at T._then (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:41710)
    at T.then (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:40066)
    at HTMLDocument.<anonymous> (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:5:78689)
pxt.reportException @ pxtapp.js:1832
pxtapp.js:1828 table: we are out of space...
pxtapp.js:1832 DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at openTransactionSafely (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:45271)
    at https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:47350
    at https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:48484
    at i (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:40024)
    at https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:40145
    at Array.forEach (<anonymous>)
    at preprocessAttachments (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:40031)
    at idbBulkDocs (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:47277)
    at PouchDB.e._bulkDocs (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:53087)
    at PouchDB.<anonymous> (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:31706)
    at PouchDB.<anonymous> (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:2836)
    at PouchDB.<anonymous> (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:206:135)
    at https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:2177
    at T.e._execute (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:15596)
    at T._resolveFromExecutor (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:45852)
From previous event:
    at T.I [as _captureStackTrace] (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:16130)
    at T._then (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:41710)
    at T.then (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:40066)
    at HTMLDocument.<anonymous> (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:5:78689)
pxt.reportException @ pxtapp.js:1832
pxtapp.js:1828 table: set failed, cleaning translation db
pxtapp.js:1832 DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at openTransactionSafely (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:45271)
    at https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:47350
    at https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:48484
    at i (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:40024)
    at https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:40145
    at Array.forEach (<anonymous>)
    at preprocessAttachments (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:40031)
    at idbBulkDocs (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:47277)
    at PouchDB.e._bulkDocs (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:53087)
    at PouchDB.<anonymous> (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:31706)
    at PouchDB.<anonymous> (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:2836)
    at PouchDB.<anonymous> (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:206:135)
    at https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:2177
    at T.e._execute (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:15596)
    at T._resolveFromExecutor (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:45852)
From previous event:
    at T.I [as _captureStackTrace] (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:16130)
    at T._then (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:41710)
    at T.then (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:40066)
    at HTMLDocument.<anonymous> (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:5:78689)
pxt.reportException @ pxtapp.js:1832
pxtapp.js:1828 table: we are out of space...
main.js:213 Uncaught DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at openTransactionSafely (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:45271)
    at PouchDB.e._get (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:53178)
    at PouchDB.<anonymous> (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:28041)
    at PouchDB.<anonymous> (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:2836)
    at PouchDB.<anonymous> (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:206:135)
    at https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:2177
    at T.e._execute (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:15596)
    at T._resolveFromExecutor (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:45852)
    at new T (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:39033)
    at PouchDB.<anonymous> (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:2082)
    at PouchDB.get (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:206:135)
    at https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:56:1099
    at c (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:72960)
    at T._settlePromiseFromHandler (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:46253)
    at T._settlePromise (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:47053)
    at T._settlePromiseCtx (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:47559)
From previous event:
    at T.I [as _captureStackTrace] (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:16130)
    at T._then (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:41710)
    at T.then (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:40066)
    at HTMLDocument.<anonymous> (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:5:78689)
t @ main.js:213
(anonymous) @ main.js:213
main.js:213 Uncaught DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at openTransactionSafely (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:45271)
    at PouchDB.e._get (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:53178)
    at PouchDB.<anonymous> (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:28041)
    at PouchDB.<anonymous> (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:2836)
    at PouchDB.<anonymous> (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:206:135)
    at https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:2177
    at T.e._execute (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:15596)
    at T._resolveFromExecutor (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:45852)
    at new T (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:39033)
    at PouchDB.<anonymous> (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:663:2082)
    at PouchDB.get (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:206:135)
    at https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:56:1099
    at c (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:72960)
    at T._settlePromiseFromHandler (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:46253)
    at T._settlePromise (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:47053)
    at T._settlePromiseCtx (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:47559)
From previous event:
    at T.I [as _captureStackTrace] (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:16130)
    at T._then (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:41710)
    at T.then (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:213:40066)
    at HTMLDocument.<anonymous> (https://pxt.azureedge.net/blob/47199b19cc06f395e6e9077d3e946d4194971d5a/main.js:5:78689)
t @ main.js:213
(anonymous) @ main.js:213
setTimeout (async)
a.throwLater @ main.js:213
a.fatalError @ main.js:213
T._reject @ main.js:213
T._settlePromise @ main.js:213
T._settlePromise0 @ main.js:213
T._settlePromises @ main.js:213
(anonymous) @ main.js:213
Promise.then (async)
r @ main.js:213
s.hasDevTools.a.settlePromises @ main.js:213
T._reject @ main.js:213
T._settlePromise @ main.js:213
T._settlePromise0 @ main.js:213
T._settlePromises @ main.js:213
(anonymous) @ main.js:213
Promise.then (async)
r @ main.js:213
s.hasDevTools.a.settlePromises @ main.js:213
T._reject @ main.js:213
T._settlePromise @ main.js:213
T._settlePromise0 @ main.js:213
T._settlePromises @ main.js:213
(anonymous) @ main.js:213
Promise.then (async)
r @ main.js:213
s.hasDevTools.a.settlePromises @ main.js:213
T._reject @ main.js:213
T._rejectCallback @ main.js:213
(anonymous) @ main.js:213
c @ main.js:213
T._settlePromiseFromHandler @ main.js:213
T._settlePromise @ main.js:213
T._settlePromise0 @ main.js:213
T._settlePromises @ main.js:213
(anonymous) @ main.js:213
Promise.then (async)
r @ main.js:213
s.hasDevTools.a.settlePromises @ main.js:213
T._reject @ main.js:213
T._rejectCallback @ main.js:213
T._settlePromiseFromHandler @ main.js:213
T._settlePromise @ main.js:213
T._settlePromise0 @ main.js:213
T._settlePromises @ main.js:213
(anonymous) @ main.js:213
Promise.then (async)
r @ main.js:213
s.hasDevTools.a.settlePromises @ main.js:213
T._reject @ main.js:213
T._settlePromise @ main.js:213
T._settlePromise0 @ main.js:213
T._settlePromises @ main.js:213
(anonymous) @ main.js:213
Promise.then (async)
r @ main.js:213
s.hasDevTools.a.settlePromises @ main.js:213
T._reject @ main.js:213
T._settlePromise @ main.js:213
T._settlePromise0 @ main.js:213
T._settlePromises @ main.js:213
(anonymous) @ main.js:213
Promise.then (async)
r @ main.js:213
s.hasDevTools.a.settlePromises @ main.js:213
T._reject @ main.js:213
T._settlePromise @ main.js:213
T._settlePromise0 @ main.js:213
T._settlePromises @ main.js:213
(anonymous) @ main.js:213
Promise.then (async)
r @ main.js:213
s.hasDevTools.a.settlePromises @ main.js:213
T._reject @ main.js:213
T._settlePromise @ main.js:213
T._settlePromise0 @ main.js:213
T._settlePromises @ main.js:213
(anonymous) @ main.js:213
Promise.then (async)
r @ main.js:213
s.hasDevTools.a.settlePromises @ main.js:213
T._reject @ main.js:213
T._resolveCallback @ main.js:213
T._settlePromiseFromHandler @ main.js:213
T._settlePromise @ main.js:213
T._settlePromiseCtx @ main.js:213
(anonymous) @ main.js:213
Promise.then (async)
r @ main.js:213
s.hasDevTools.a.invoke @ main.js:213
T._then @ main.js:213
T.then @ main.js:213
t.getAsync @ main.js:56
getAsync @ main.js:20
fixupVersionAsync @ main.js:182
(anonymous) @ main.js:182
(anonymous) @ pxtapp.js:1119
(anonymous) @ pxtapp.js:1130
e._execute @ main.js:213
T._resolveFromExecutor @ main.js:213
T @ main.js:213
PromiseQueue.enqueue @ pxtapp.js:1113
saveAsync @ main.js:182
t.saveFilesAsync @ main.js:128
t.setContentAsync @ main.js:128
(anonymous) @ main.js:5
c @ main.js:213
T._settlePromiseFromHandler @ main.js:213
T._settlePromise @ main.js:213
T._settlePromise0 @ main.js:213
T._settlePromises @ main.js:213
(anonymous) @ main.js:213
Promise.then (async)
r @ main.js:213
s.hasDevTools.a.settlePromises @ main.js:213
T._fulfill @ main.js:213
T._resolveCallback @ main.js:213
T._settlePromiseFromHandler @ main.js:213
T._settlePromise @ main.js:213
T._settlePromiseCtx @ main.js:213
(anonymous) @ main.js:213
Promise.then (async)
r @ main.js:213
s.hasDevTools.a.invoke @ main.js:213
T._then @ main.js:213
T.then @ main.js:213
(anonymous) @ main.js:5
c @ main.js:213
T._settlePromiseFromHandler @ main.js:213
T._settlePromise @ main.js:213
T._settlePromise0 @ main.js:213
T._settlePromises @ main.js:213
(anonymous) @ main.js:213
Promise.then (async)
r @ main.js:213
s.hasDevTools.a.settlePromises @ main.js:213
T._fulfill @ main.js:213
T._resolveCallback @ main.js:213
T._settlePromiseFromHandler @ main.js:213
T._settlePromise @ main.js:213
T._settlePromiseCtx @ main.js:213
(anonymous) @ main.js:213
Promise.then (async)
r @ main.js:213
s.hasDevTools.a.invoke @ main.js:213
T._then @ main.js:213
T.then @ main.js:213
e.saveTypeScriptAsync @ main.js:5
e.saveFileAsync @ main.js:5
(anonymous) @ main.js:5
c @ main.js:213
T._settlePromiseFromHandler @ main.js:213
T._settlePromise @ main.js:213
T._settlePromise0 @ main.js:213
T._settlePromises @ main.js:213
(anonymous) @ main.js:213
Promise.then (async)
r @ main.js:213
s.hasDevTools.a.settlePromises @ main.js:213
T._fulfill @ main.js:213
T._resolveCallback @ main.js:213
T._settlePromiseFromHandler @ main.js:213
T._settlePromise @ main.js:213
T._settlePromise0 @ main.js:213
T._settlePromises @ main.js:213
(anonymous) @ main.js:213
Promise.then (async)
r @ main.js:213
s.hasDevTools.a.settlePromises @ main.js:213
T._fulfill @ main.js:213
T._resolveCallback @ main.js:213
T._settlePromiseFromHandler @ main.js:213
T._settlePromise @ main.js:213
T._settlePromise0 @ main.js:213
T._settlePromises @ main.js:213
(anonymous) @ main.js:213
Promise.then (async)
r @ main.js:213
s.hasDevTools.a.settlePromises @ main.js:213
T._fulfill @ main.js:213
T._resolveCallback @ main.js:213
T._settlePromiseFromHandler @ main.js:213
T._settlePromise @ main.js:213
T._settlePromise0 @ main.js:213
T._settlePromises @ main.js:213
(anonymous) @ main.js:213
Promise.then (async)
r @ main.js:213
s.hasDevTools.a.settlePromises @ main.js:213
T._fulfill @ main.js:213
T._resolveCallback @ main.js:213
(anonymous) @ main.js:213
(anonymous) @ pxtapp.js:3043
DevTools failed to parse SourceMap: https://pxt.azureedge.net/blob/dd22520c096be24e7432f5b46e8aad59711f31f0/ai.0.js.map
```

**Expected behavior**
It should load the editor page successfully.

**Screenshots**
always loading:
![always loading](https://user-images.githubusercontent.com/40351998/53476856-3d1e2780-3a28-11e9-9d8f-5176df569d1b.PNG)

**Desktop (please complete the following information):**
 - Device:  PC
 - OS: Win10
 - Browser: Chrome

**Additional context**
None

**Comment by xuefengedu** [comment]
Fixed now, just close it.
