### ISSUE TITLE
locally hosted website using ptxserve tries to use live azure resources to compile hex file

### ISSUE THREAD

**Issue by gingemonster** [Microsoft/pxt-microbit#215]
If you setup the repo on you local machine (Ive tried windows and osx) using the readme instructions and run:

"pxt serve -yt"

The site opens and you can code using it but when you click "download" to compile the hex it tries to use the online azure resources to compile calling this url:

https://az851932.vo.msecnd.net/compile/3ab51b196b0c87af4a89fc6aeb06d6b9078f7347c64b7a0697cfa0fb80d1d699.hex 

and the ajax promise fails with:

Unhandled rejection Error: {
 "success": false,
 "hexurl": "",
 "mbedresponse": {
  "result": {
   "exception": "info: get versions for bbc-microbit-classic-gcc\ninfo: download bbc-microbit-classic-gcc@0.2.3 from the public module registry\ninfo: get versions for mbed-gcc\ninfo: download mbed-gcc@0.1.3 from the public module registry\ninfo: get versions for bbc-microbit-classic-gcc\ninfo: get versions for mbed-gcc\ninfo: get versions for pxt-microbit-core\ninfo: download pxt-microbit-core@v0.3.1 from GitHub Microsoft/pxt-microbit-core\ninfo: get versions for microbit\ninfo: download microbit@v2.0.0-rc4 from GitHub lancaster-university/microbit\ninfo: get versions for microbit-dal\ninfo: download microbit-dal@v2.0.0-rc4 from GitHub lancaster-university/microbit-dal\ninfo: get versions for mbed-classic\ninfo: download mbed-classic@microbit_hfclk+mb5 from GitHub lancaster-university/mbed-classic\nerror: failed to extract tarfile [Errno 28] No space left on device\nFatal Exception, yotta=0.14.1\nTraceback (most recent call last):\n  File \"/usr/local/bin/yotta\", line 4, in <module>\n    yotta.main()\n  File \"/usr/local/lib/python2.7/dist-packages/yotta/main.py\", line 201, in main\n    status = args.command(args, following_args)\n  File \"/usr/local/lib/python2.7/dist-packages/yotta/update.py\", line 43, in execCommand\n    updateDeps(c, target, args)\n  File \"/usr/local/lib/python2.7/dist-packages/yotta/update.py\", line 60, in updateDeps\n    test = update_test_deps\n  File \"/usr/local/lib/python2.7/dist-packages/yotta/lib/component.py\", line 655, in satisfyDependenciesRecursive\n    test = test\n  File \"/usr/local/lib/python2.7/dist-packages/yotta/lib/component.py\", line 440, in __getDependenciesRecursiveWithProvider\n    _processed = _processed\n  File \"/usr/local/lib/python2.7/dist-packages/yotta/lib/component.py\", line 440, in __getDependenciesRecursiveWithProvider\n    _processed = _processed\n  File \"/usr/local/lib/python2.7/dist-packages/yotta/lib/component.py\", line 440, in __getDependenciesRecursiveWithProvider\n    _processed = _processed\n  File \"/usr/local/lib/python2.7/dist-packages/yotta/lib/component.py\", line 419, in __getDependenciesRecursiveWithProvider\n    test = test\n  File \"/usr/local/lib/python2.7/dist-packages/yotta/lib/component.py\", line 319, in __getDependenciesWithProvider\n    satisfyDep, specs\n  File \"/usr/local/lib/python2.7/dist-packages/yotta/lib/component.py\", line 295, in satisfyDep\n    self\n  File \"/usr/local/lib/python2.7/dist-packages/yotta/lib/component.py\", line 640, in provider\n    inherit_shrinkwrap = dep_of.getShrinkwrap()\n  File \"/usr/local/lib/python2.7/dist-packages/yotta/lib/access.py\", line 317, in satisfyVersionByInstalling\n    name, version_required, install_into, v, type=type, inherit_shrinkwrap = inherit_shrinkwrap\n  File \"/usr/local/lib/python2.7/dist-packages/yotta/lib/access.py\", line 332, in _satisfyVersionByInstallingVersion\n    'Dependency \"%s\":\"%s\" is not a valid %s.' % (name, version_required, type)\nException: Dependency \"mbed-classic\":\"lancaster-university/mbed-classic#microbit_hfclk+mb5\" is not a valid module.\n"
  }
 },
 "bugReportId": ""
}
    at Object.userError (http://localhost:3232/cdn/pxtlib.js:485:25)
    at http://localhost:3232/cdn/pxtlib.js:1646:35
    at r (http://localhost:3232/cdn/bluebird.min.js:31:7722)
    at i._settlePromiseFromHandler (http://localhost:3232/cdn/bluebird.min.js:30:13044)
    at i._settlePromise (http://localhost:3232/cdn/bluebird.min.js:30:13847)
    at i._settlePromise0 (http://localhost:3232/cdn/bluebird.min.js:30:14548)
    at i._settlePromises (http://localhost:3232/cdn/bluebird.min.js:30:15878)
    at r._drainQueue (http://localhost:3232/cdn/bluebird.min.js:29:3148)
    at r._drainQueues (http://localhost:3232/cdn/bluebird.min.js:29:3209)
    at drainQueues (http://localhost:3232/cdn/bluebird.min.js:29:1238)

In my testing, very very occasionly, it magically works and does actually compile and upload locally but its perhaps 1 in 10 times at best.

**Comment by gingemonster** [comment]
After more testing I have a way to replicate this and it seems related to having yotta ever build on my machine

1) pull down the repo with no changes
2) run pxt serve -yt (hex files downloading and uploading fine)
3) make a very simple change to a cpp file
4) yotta build will automatically build (no errors) (hex files downloading and uploading fine)
5) quit out of "pxt serve -yt"
6) restart "pxt serve -yt"
7) now hex files will not compile locally but instead you get the errors above

git resetting will get everything working again
