### ISSUE TITLE
pxt target microbit     - broken?

### ISSUE THREAD

**Issue by bennytheshap** [microsoft/pxt-microbit#2381]
**Describe the bug**
I just setup a new pxt environment (different computer) and `pxt target microbit` seems to result in a broken install. `microbit/node_modules/pxt-microbit/libs/core/pxt.json` is missing.

**To Reproduce**
Follow the instructions from https://makecode.com/cli
in particular:
```
npm install -g pxt
mkdir microbit
cd microbit
pxt target microbit
pxt serve
```

**Expected behavior**
A working MakeCode instance, running from localhost.

**What happens instead**
I get the initial MakeCode web interface, but node crashes with this error:
```
INTERNAL ERROR: Error: ENOENT: no such file or directory, open '/Users/ben/devel/microbit/node_modules/pxt-microbit/libs/core/pxt.json'
    at Object.openSync (fs.js:447:3)
    at Object.readFileSync (fs.js:349:35)
    at readJson (/Users/ben/devel/microbit/node_modules/pxt-core/built/nodeutil.js:267:26)
    at readPkgConfig (/Users/ben/devel/microbit/node_modules/pxt-core/built/nodeutil.js:273:14)
    at Object.resolveMd (/Users/ben/devel/microbit/node_modules/pxt-core/built/nodeutil.js:493:19)
    at readMd (/Users/ben/devel/microbit/node_modules/pxt-core/built/server.js:823:28)
    at Server.<anonymous> (/Users/ben/devel/microbit/node_modules/pxt-core/built/server.js:1059:22)
    at Server.emit (events.js:203:13)
    at parserOnIncoming (_http_server.js:733:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
``` 

Scrolling up a bit, I notice this error too:
```
*** Build failed: target build failed: ENOENT: no such file or directory, scandir 'libs'
Error: ENOENT: no such file or directory, scandir 'libs'
    at Object.readdirSync (fs.js:795:3)
    at Object.allFiles (/Users/ben/devel/microbit/node_modules/pxt-core/built/nodeutil.js:355:30)
    at updateDefaultProjects (/Users/ben/devel/microbit/node_modules/pxt-core/built/pxt.js:147438:14)
    at buildTargetCoreAsync (/Users/ben/devel/microbit/node_modules/pxt-core/built/pxt.js:147509:5)
    at /Users/ben/devel/microbit/node_modules/pxt-core/built/pxt.js:147004:95
    at tryCatcher (/Users/ben/devel/microbit/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/ben/devel/microbit/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/ben/devel/microbit/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/ben/devel/microbit/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/ben/devel/microbit/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/ben/devel/microbit/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/ben/devel/microbit/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/ben/devel/microbit/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:439:21)
***

```
**Desktop**
 - OS: MacOS 10.14.6
 - Browser: Irrelevant
 - Version: Irrelevant

**Additional context**
Node version is 12.7.0.

**Comment by JeffBrilliantLabs** [comment]
Hello, 

Not sure this is a bug or an issue and more of a support request but if those are the exact build steps you used they are diff than the ones suggested... 

You seem to have used:
npm install -g pxt
mkdir microbit
cd microbit
pxt target microbit
pxt serve

I take it your npm install -g pxt was after you cloned the pxt repo but did you also install the dependencies like outlined below?

This is where you started: npm install -g pxt

You seem to have forgotten the step #8: 

Install the pxt-microbit dependencies.
**npm install**

If that still doesn't work you may want to try step 8b which links pxt and pxt-common-packages... 

Good luck!
