### ISSUE TITLE
Hangs and errors in second MakeCode window

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microsoft/pxt-microbit#2529]
**Describe the bug**

The Micro:bit Educational Foundation are developing a web app that embeds Makecode via controller=1.

For onboarding and demo scenarios, we'd like our teacher users to play two roles, in order to experience the app as a teacher and a student in separate browser tabs or windows. Both scenarios involve an embedded MakeCode editor.

We experience various failures when doing this that relate to calls to `checkSession` in the first window/tab after opening a second window/tab.

## Failure scenarios

One reproduction is as I reported a while back on https://github.com/microsoft/pxt/issues/5462 (easier to reproduce with windows not tabs, though I don't see why).

The other cases below have been reproduced using controller=1 by loading two MakeCode windows side-by-side just after each other.

### Hang during MakeCode initialisation

We've seen this one a few times in demos and user testing.

I've also seen a variant where more MakeCode UI elements are initialized but it still hangs before the loading mask is removed.

![image](https://user-images.githubusercontent.com/44397098/69225471-63679280-0b76-11ea-8e0c-665d8745d268.png)

```
Uncaught Error: trying to access outdated session
    at Object.assert (https://pxt.azureedge.net/blob/445d11e4efcff6862d2e0751b7afb19afcaaadae/pxtapp.js:252:27)
    at checkSession (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:296:4207)
    at Object.getHeader (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:296:3982)
    at https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:5:93484
    at Array.filter (<anonymous>)
    at https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:5:93447
    at c (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:324:72960)
    at T._settlePromiseFromHandler (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:324:46253)
    at T._settlePromise (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:324:47053)
    at T._settlePromise0 (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:324:47752)
    at T._settlePromises (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:324:49079)
    at https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:324:2811
From previous event:
    at T.I [as _captureStackTrace] (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:324:16130)
    at T._then (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:324:41710)
    at T.then (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:324:40066)
    at HTMLDocument.<anonymous> (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:5:93393)
```

### Broken simulator

In this case the simulator spins indefinitely.

Note switching away from the tab and back (but not window) reinitialises the simulator.

![image](https://user-images.githubusercontent.com/44397098/69226120-8e061b00-0b77-11ea-922f-d9758d641dc6.png)

```
Uncaught Error: trying to access outdated session
    at Object.assert (https://pxt.azureedge.net/blob/445d11e4efcff6862d2e0751b7afb19afcaaadae/pxtapp.js:252:27)
    at checkSession (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:296:4207)
    at Object.saveAsync (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:296:5785)
    at t.saveFilesAsync (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:224:7803)
    at t.setContentAsync (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:224:1804)
    at t.writeFile (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:224:9259)
    at MainPackage.Package.saveConfig (https://pxt.azureedge.net/blob/445d11e4efcff6862d2e0751b7afb19afcaaadae/pxtapp.js:9829:25)
    at MainPackage.Package.setPreferredEditor (https://pxt.azureedge.net/blob/445d11e4efcff6862d2e0751b7afb19afcaaadae/pxtapp.js:9834:22)
    at e.syncPreferredEditor (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:5:37980)
    at https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:5:59203
    at e.runSimulator (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:5:60444)
    at e.<anonymous> (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:5:4036)
    at e.autoRunSimulatorDebounced (https://pxt.azureedge.net/blob/445d11e4efcff6862d2e0751b7afb19afcaaadae/pxtapp.js:1052:30)
    at https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:5:4676
    at c (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:324:72960)
    at T._settlePromiseFromHandler (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:324:46253)
From previous event:
    at T.I [as _captureStackTrace] (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:324:16130)
    at T._then (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:324:41710)
    at T.done (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:324:40135)
    at e.<anonymous> (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:5:4305)
    at later (https://pxt.azureedge.net/blob/445d11e4efcff6862d2e0751b7afb19afcaaadae/pxtapp.js:1046:34)
```

### Logged errors in other cases

If you load the second MakeCode well after the first to avoid the errors above then you still get errors on the console for key user actions that make me concerned as to whether MakeCode is functioning correctly. For example, making an edit to blocks in the first window:

```
Uncaught Error: trying to access outdated session
    at Object.assert (https://pxt.azureedge.net/blob/445d11e4efcff6862d2e0751b7afb19afcaaadae/pxtapp.js:252:27)
    at checkSession (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:296:4207)
    at Object.saveAsync (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:296:5785)
    at t.saveFilesAsync (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:224:7803)
    at t.setContentAsync (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:224:1804)
    at https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:224:6484
    at c (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:324:72960)
    at T._settlePromiseFromHandler (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:324:46253)
    at T._settlePromise (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:324:47053)
    at T._settlePromiseCtx (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:324:47559)
    at https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:324:2692
From previous event:
    at T.I [as _captureStackTrace] (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:324:16130)
    at T._then (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:324:41710)
    at T.then (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:324:40066)
    at e.saveTypeScriptAsync (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:5:47259)
    at e.saveFileAsync (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:5:12108)
    at e.<anonymous> (https://pxt.azureedge.net/blob/596960afef81693fdb89b79bb3ef56583d6edbae/main.js:5:4979)
    at later (https://pxt.azureedge.net/blob/445d11e4efcff6862d2e0751b7afb19afcaaadae/pxtapp.js:1046:34)
```

**Expected behavior**

We'd like to be able to use MakeCode in this scenario. As a first step I'd love input as to whether this is supposed to work, for ordinary use of MakeCode and for the controller=1 case.

The root seems to be the shared local storage between the tabs. I'm working on the assumption that checkSession is a guard to prevent continuing when MakeCode might not be aware of state changes from other tabs.

Possible options to enable this scenario:

1. MakeCode copes, e.g. by reinitialising itself when it hits these issues. This might address the issue for all users not just the controller=1 case.
2. Provide some means to isolate the local storage for the teacher vs student usecases. Ideas:
    (a) A URL option to switch to the in-memory local storage (MemoryStorage) for the scenario where a teacher tries out the student scenario might be a simple option.
    (b) Delegate the storage to the iframe embedder via postMessage? Could be painful as it would be async but isn't currently.
    (c) Provide some way to scope the storage internally, e.g. a prefix

**Desktop (please complete the following information):**
 - macOs
 - Chrome 
 -  78.0.3904.97 (Official Build) (64-bit)

This is what I used to reproduce but users have seen the issue on a variety of platforms and browsers.

**Comment by gbraad** [comment]
A shared session between tabs, even when working on a different project (like a remote and a receiver) can result in data loss.

**Comment by abchatra** [comment]
This should be fixed in latest /beta. We have made many improvements.
