### ISSUE TITLE
WebUSB: split of undefined

### ISSUE THREAD

**Issue by pelikhan** [microsoft/pxt-microbit#3412]
It looks like we try to get the wrong binFile
```
            // TODO this is seriously inefficient (130ms on a fast machine)
            var uf2 = ts.pxtc.UF2.newBlockFile();
            var binFile = resp.outfiles[_this.binName];
            ts.pxtc.UF2.writeHex(uf2, binFile.split(/\r?\n/));
            var bytes = pxt.U.stringToUint8Array(ts.pxtc.UF2.serializeFile(uf2));
            var parsed = ts.pxtc.UF2.parseFile(bytes);
```

```
react_devtools_backend.js:2273 TypeError: Cannot read property 'split' of undefined
    at http://localhost:3232/cdn/editor.js:3460:47
From previous event:
    at DAPWrapper.quickHidFlashAsync (http://localhost:3232/cdn/editor.js:3455:14)
    at http://localhost:3232/cdn/editor.js:3366:26
From previous event:
    at DAPWrapper.reflashAsync (http://localhost:3232/cdn/editor.js:3361:14)
    at http://localhost:3232/blb/main.js:8735:104
From previous event:
    at deployAsync (http://localhost:3232/blb/main.js:8735:14)
    at hidDeployCoreAsync (http://localhost:3232/blb/main.js:8732:12)
    at Object.commands.deployAsync (http://localhost:3232/blb/pxtapp.js:4503:78)
    at http://localhost:3232/blb/main.js:2706:37
From previous event:
    at ProjectView.compile (http://localhost:3232/blb/main.js:2688:16)
    at EditorToolbar.compile (http://localhost:3232/blb/main.js:18354:27)
    at EditorToolbarButton.handleClick (http://localhost:3232/blb/main.js:18578:9)
    at HTMLUnknownElement.callCallback (http://localhost:3232/blb/main.js:76346:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3232/blb/main.js:76395:16)
    at invokeGuardedCallback (http://localhost:3232/blb/main.js:76450:31)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:3232/blb/main.js:76464:25)
    at executeDispatch (http://localhost:3232/blb/main.js:76594:3)
    at executeDispatchesInOrder (http://localhost:3232/blb/main.js:76619:5)
    at executeDispatchesAndRelease (http://localhost:3232/blb/main.js:76723:5)
    at executeDispatchesAndReleaseTopLevel (http://localhost:3232/blb/main.js:76732:10)
    at forEachAccumulated (http://localhost:3232/blb/main.js:76704:8)
    at runEventsInBatch (http://localhost:3232/blb/main.js:76749:3)
    at runExtractedPluginEventsInBatch (http://localhost:3232/blb/main.js:76890:3)
    at handleTopLevel (http://localhost:3232/blb/main.js:81817:5)
    at batchedEventUpdates$1 (http://localhost:3232/blb/main.js:100378:12)
    at batchedEventUpdates (http://localhost:3232/blb/main.js:77429:12)
    at dispatchEventForPluginEventSystem (http://localhost:3232/blb/main.js:81908:5)
    at attemptToDispatchEvent (http://localhost:3232/blb/main.js:82024:5)
```

**Comment by pelikhan** [comment]
Added logging.
