### ISSUE TITLE
Sound editor block replace

### ISSUE THREAD

**Issue by ElizabethRiffle** [microsoft/pxt-microbit#4522]
**To Reproduce**
1. Drag out a play sound block
2. Drag out just a sound editor block and replace the current sound editor block in the play sound block

**Screenshots**
![image](https://user-images.githubusercontent.com/14082525/163603764-0be85670-fa43-43fe-9943-ccb9dda3366a.png)
![image](https://user-images.githubusercontent.com/14082525/163603854-9237b9af-cc47-4ace-993f-c0216a805b9b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 7.5.14

**Comment by dmonroym** [comment]
Similarly when I create a new project I now see that block but can't move or delete it:

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/3288375/163604459-32aaa169-0822-4fac-93d0-074180a96653.png">


```
pxtapp.js:1 
        
       Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://trg-microbit.userpxt.io') does not match the recipient window's origin ('https://makecode.microbit.org').
postMessageCore @ pxtapp.js:1
pxtapp.js:1 
        
       Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://trg-microbit.userpxt.io') does not match the recipient window's origin ('https://makecode.microbit.org').
postMessageCore @ pxtapp.js:1
pxtapp.js:1 
        
       Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://trg-microbit.userpxt.io') does not match the recipient window's origin ('https://makecode.microbit.org').
postMessageCore @ pxtapp.js:1
pxtblockly.js:1 
        
       Uncaught TypeError: Cannot read properties of null (reading 'isSelectable')
    at Object.onClick_ (pxtblockly.js:1:510260)
    at HTMLDivElement.r (pxtblockly.js:1:54692)
pxtblockly.js:53 
        
       Uncaught (in promise) TypeError: Cannot read properties of null (reading 'removeChangeListener')
    at n.onDispose (pxtblockly.js:53:239917)
    at n.dispose (pxtblockly.js:53:163814)
    at Object.dispose (pxtblockly.js:1:290835)
    at Object.dispose (pxtblockly.js:1:293551)
    at Object.dispose (pxtblockly.js:1:351064)
    at Object.dispose (pxtblockly.js:1:293499)
    at Object.dispose (pxtblockly.js:1:351064)
    at Object.clear (pxtblockly.js:1:180010)
    at Object.clear (pxtblockly.js:1:407300)
    at Object.clearWithoutEvents (pxtblockly.js:53:75244)
pxtblockly.js:1 
        
       Uncaught TypeError: Cannot read properties of null (reading 'isDragging')
    at Object.bumpAwayFrom (pxtblockly.js:1:330874)
    at Object.bumpNeighbours (pxtblockly.js:1:358709)
    at pxtblockly.js:1:359013
```
