### ISSUE TITLE
extensions: removing extension can delete all program contents

### ISSUE THREAD

**Issue by eanders-ms** [microsoft/pxt-microbit#4585]
OS: Windows 11
Browser: Chrome

Repro steps:
1. Create new project
2. Add a basic block to `on start`, like `show leds` (just to make it more obvious when it everything gets deleted)
3. Add the "robotbit" extension. Note: This will also install "neopixel"
4. Add a block from Neopixel to your project
5. Remove the Robotbit extension by clicking on the `(x)` button that appears on hover
6. Notice the whole program is deleted

Expected: Only the block from Neopixel would be deleted

Error from dev console:
```
TypeError: Unknown block type: neopixel_create
    at Object.<anonymous> (pxtblockly.js:1:292013)
    at new <anonymous> (pxtblockly.js:1:339871)
    at Object.newBlock (pxtblockly.js:1:387417)
    at Object.domToBlockHeadless_ (pxtblockly.js:1:92824)
    at Object.applyInputTagNodes_ (pxtblockly.js:1:91972)
    at Object.domToBlockHeadless_ (pxtblockly.js:1:93407)
    at Object.applyInputTagNodes_ (pxtblockly.js:1:91972)
    at Object.domToBlockHeadless_ (pxtblockly.js:1:93407)
    at Object.domToBlock (pxtblockly.js:1:88922)
    at Object.domToWorkspace (pxtblockly.js:1:87082)
```

**Comment by abchatra** [comment]
Removed the option to delete for now.
