### ISSUE TITLE
Beta: WebUSB flashing failures

### ISSUE THREAD

**Issue by martinwork** [microsoft/pxt-microbit#4679]
**Describe the bug**
I am seeing WebUSB flashing failures with beta that don't seem to happen with live.

This happens more often than not when re-opening MakeCode beta and attempting a Download, after previously doing a WebUSB flash with MakeCode beta. I haven't found a good way to clear the error: unplug, disconnect WebUSB, close MakeCode, change USB socket, etc. don't always work. I've restarted the computer a couple of times.

**To Reproduce**
1. Open MakeCode beta
2. Download using WebUSB
2. Close MakeCode
3. Open MakeCode beta
4. Download again

**Expected behavior**
WebUSB download usually works.

**micro:bit version (please complete the following information):**

You can find this information in the lower right hand corner of the back of micro:bit (the side that says BBC micro:bit).
 - Which version of the micro:bit is this relevant to [ EG V1.3, V1.5, V2.0, or specify it's not hardware related ]

Tested V2.0 and V2.20

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

```
pxtapp.js:1 webusb: get devices
editor.js:2415 Connecting...
editor.js:2446 Connected
editor.js:2391 Uncaught (in promise) Error: Bad response for 5 -> 131
    at CMSISDAP.<anonymous> (editor.js:2391:35)
    at step (editor.js:2317:23)
    at Object.next (editor.js:2298:53)
    at fulfilled (editor.js:2289:58)
sim.js:113 detected v2 feature Array(1)
sim.js:113 detected v2 feature Array(1)
sim.js:113 detected v2 feature Array(1)
sim.js:113 detected v2 feature Array(1)
sim.js:113 detected v2 feature Array(1)
sim.js:113 detected v2 feature Array(1)
editor.js:2415 Connecting...
editor.js:3265 Error: bad dapCmd response: 131 -> 5
    at editor.js:3429:27
    at async DAPWrapper.readSerial (editor.js:3209:19)
    at async readSerialLoop (editor.js:3255:33)
readSerialLoop @ editor.js:3265
DevTools failed to load source map: Could not load content for https://pxt.azureedge.net/commit/9891f3eb59055be837d12f376ef340c27dc506e4/dapjs.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

```

or this
```
editor.js:2391 Uncaught (in promise) Error: Bad response for 5 -> 9
    at CMSISDAP.<anonymous> (editor.js:2391:35)
    at step (editor.js:2317:23)
    at Object.next (editor.js:2298:53)
    at fulfilled (editor.js:2289:58)
(anonymous) @ editor.js:2391
step @ editor.js:2317
(anonymous) @ editor.js:2298
fulfilled @ editor.js:2289
editor.js:2415 Connecting...
editor.js:3265 Error: bad dapCmd response: 9 -> 5
    at editor.js:3429:27
    at async DAPWrapper.jacdacProcess (editor.js:3800:17)
    at async readSerialLoop (editor.js:3259:21)
readSerialLoop @ editor.js:3265
await in readSerialLoop (async)
startReadSerial @ editor.js:3281
reconnectAsync @ editor.js:3344
pxtapp.js:1 
```

**Comment by abchatra** [comment]
@pelikhan recent changes?

**Comment by pelikhan** [comment]
Probably will investigate
________________________________

**Comment by pelikhan** [comment]
This should be fixed with the recent update.
