### ISSUE TITLE
erroneous "incompatible code" errors on micro:bit V2

### ISSUE THREAD

**Issue by jaustin** [microsoft/pxt-microbit#4680]
In certain cases that I can't pin down a root cause for (usually when un/replugging my micro:bit to test data logging) I sometimes get MakeCode telling me that I have incompatible code. If I reload MakeCode and un/replug in the same micro:bit, the error goes away.

@pelikhan or @mmoskal is there sensible debug that I should get for you to work out what's going on here? I can't reliably reproduce it, so would be good to know what to dump from where when it happens again. (It's happened 3 times in the last few hours of working with MakeCode)

![Screenshot2022_05_20_184628](https://user-images.githubusercontent.com/147113/169804865-52967054-5ed7-4821-88ed-7cdce62fbf6b.jpg)

(I have the datalog extension added)

**Comment by pelikhan** [comment]
Add  ?webusbdbg=1 to the url to get more logging

**Comment by martinwork** [comment]
Testing V2.0 with 0255 and beta makecode.microbit.org version:  [4.1.41](https://github.com/Microsoft/pxt-microbit/releases/tag/v4.1.41)

Pair with micro:bit and download a project. Keep micro: powered with a battery. Repeatedly disconnect and connect USB.

On each connection the console shows "get devices", and it should say "Connecting..., Connected".
Sometimes it doesn't, and then Download either complains "incompatible code", or there's a "Error: Bad response for 0 -> 128" and it reverts to saving a file. Cycling the connection again usually says "Connecting..., Connected", and Download works.

I think the report is "incompatible code" when the project loaded in MakeCode is a datalogging one.

**Comment by martinwork** [comment]
It's happened with V2.20+0257 too, and right now reconnecting isn't clearing it.

**Comment by martinwork** [comment]
I think it's the same with MakeCode live.

**Comment by pelikhan** [comment]
Could you add ?webusbdbg=1 to the url and collect the javascript console output?

**Comment by martinwork** [comment]
get devices sometimes fails with MakeCode live too, but the download error is "Error: Bad response for 0 -> 128" even with a datalogging project.

**Comment by martinwork** [comment]
It doesn't look any different, so I'm probably doing it wrong. Can you explain "Could you add ?webusbdbg=1 to the url and collect the javascript console output?" for someone who doesn't know what that means?!
```
webusb: get devices
pxtapp.js:1 Uncaught (in promise) Error: Device not found.
    at o.connectAsync (pxtapp.js:1:371084)
    at pxtapp.js:1:370739
    at async DAPWrapper.reconnectAsync (editor.js:3313:9)
    at async readSerialLoop (editor.js:3272:25)
connectAsync @ pxtapp.js:1
(anonymous) @ pxtapp.js:1
await in (anonymous) (async)
startReadSerial @ editor.js:3277
reconnectAsync @ editor.js:3338
pxtapp.js:1 webusb: get devices
editor.js:2415 Connecting...
editor.js:2446 Connected
/?webusbdbg=1#editor:1 Uncaught (in promise) DOMException: A transfer error has occurred.
pxtapp.js:1 webusb: get devices
editor.js:2415 Connecting...
editor.js:2446 Connected
/?webusbdbg=1#editor:1 Uncaught (in promise) DOMException: A transfer error has occurred.
pxtapp.js:1 webusb: get devices
sim.js:113 detected v2 feature ['flashlog']
editor.js:2415 Connecting...
pxtapp.js:1 Error: Bad response for 0 -> 128
    at CMSISDAP.<anonymous> (editor.js:2391:35)
    at step (editor.js:2317:23)
    at Object.next (editor.js:2298:53)
    at fulfilled (editor.js:2289:58)
e.reportException @ pxtapp.js:1
e.reportException @ pxtapp.js:1
(anonymous) @ main.js:1
Promise.catch (async)
k @ main.js:1
e.deployAsync @ pxtapp.js:1
compile @ main.js:1
await in compile (async)
compile @ main.js:1
onDownloadButtonClick @ main.js:1
handleClick @ main.js:1
m @ main.js:1
k @ main.js:1
(anonymous) @ main.js:1
_ @ main.js:1
N @ main.js:1
T @ main.js:1
O @ main.js:1
Cn @ main.js:1
ce @ main.js:1
On @ main.js:1
In @ main.js:1
Pn @ main.js:1
n.unstable_runWithPriority @ main.js:1
Kr @ main.js:1
ae @ main.js:1
An @ main.js:1
```

**Comment by martinwork** [comment]
I've actually run out of time - gotta go! This is after choosing "Verbose" with 2.00+0255:

```
compiling...
main.js:1 sim: stop (autorun true)
pxtapp.js:1 building: core, flashlog, datalogger, microphone, radio, livelog
pxtapp.js:1 app variant: mbdal
pxtapp.js:1 disable variant mbdal due to datalogger
pxtapp.js:1 disable variant mbdal due to flashlog
pxtapp.js:1 disable variant mbdal due to this
pxtapp.js:1 Using cached extinfo
pxtapp.js:1 app variant: undefined
pxtapp.js:1 building for mbcodal
pxtapp.js:1 app variant: mbcodal
pxtapp.js:1 Using cached extinfo
pxtapp.js:1 app variant: undefined
pxtapp.js:1 [Violation] 'setTimeout' handler took 90ms
main.js:1 worker op: compile
main.js:1 worker op done: compile
main.js:1 sim: start run (autorun true, first false)
main.js:1 cmds: hid deploy
pxtapp.js:1 packetio: init 
pxtapp.js:1 building: core, flashlog, datalogger, microphone, radio, livelog
pxtapp.js:1 app variant: mbdal
pxtapp.js:1 disable variant mbdal due to datalogger
pxtapp.js:1 disable variant mbdal due to flashlog
pxtapp.js:1 disable variant mbdal due to this
pxtapp.js:1 Using cached extinfo
pxtapp.js:1 app variant: undefined
pxtapp.js:1 building for mbcodal
pxtapp.js:1 app variant: mbcodal
pxtapp.js:1 Using cached extinfo
pxtapp.js:1 app variant: undefined
editor.js:3134 dap 13456: reflash
main.js:1 worker op: compile
editor.js:3134 dap 00000: cancelling serial reader 13
main.js:1 worker op done: compile
main.js:1 sim: run
sim.js:113 detected v2 feature ['flashlog']
pxtsim.js:1 No available 5V pin on board!
editor.js:2415 Connecting...
editor.js:3134 dap 00202: bad dapCmd response: 128 -> 0; retrying
main.js:1 showloading: hiddeploy
[Violation] Forced reflow while executing JavaScript took 33ms

```

**Comment by martinwork** [comment]
Here are good and bad logs, when trying to flash a datalogging project and a simple project
In each case I recorded disconnect USB, connect USB, Download
[datalog_good.log](https://github.com/microsoft/pxt-microbit/files/8772658/datalog_good.log)
[datalog_bad.log](https://github.com/microsoft/pxt-microbit/files/8772659/datalog_bad.log)
[good.log](https://github.com/microsoft/pxt-microbit/files/8772660/good.log)
[bad.log](https://github.com/microsoft/pxt-microbit/files/8772661/bad.log)
