### ISSUE TITLE
Building target locally fails

### ISSUE THREAD

**Issue by microbit-carlos** [microsoft/pxt-microbit#5915]
This also affects the CODAL CI, a commit that built successfully 3 weeks ago:
https://github.com/lancaster-university/codal-microbit-v2/actions/runs/10404959248/attempts/2
Now fails:
https://github.com/lancaster-university/codal-microbit-v2/actions/runs/10404959248/job/29750283461

To replicate (this fails with or without docker, i.e. `PXT_NODOCKER=1`):

```bash
git clone https://github.com/microsoft/pxt-microbit.git
cd pxt-microbit
npm install pxt --no-save
npm install
PXT_NODOCKER=1 PXT_FORCE_LOCAL=1 npx pxt buildtarget --local
```
The error output:
```
removing stale /source/radio/radio.cpp
*** yotta target bbc-microbit-classic-gcc@https://github.com/lancaster-university/yotta-target-bbc-microbit-classic-gcc
INTERNAL ERROR: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at Hash.update (node:internal/crypto/hash:109:11)
    at Object.sha256 (/Users/microbit-carlos/workspace/tmp/pxt-error/pxt-microbit/node_modules/pxt-core/built/nodeutil.js:229:10)
    at Object.buildHexAsync (/Users/microbit-carlos/workspace/tmp/pxt-error/pxt-microbit/node_modules/pxt-core/built/buildengine.js:241:20)
    at Host.getHexInfoAsync (/Users/microbit-carlos/workspace/tmp/pxt-error/pxt-microbit/node_modules/pxt-core/built/pxt.js:163455:22)
    at fillExtInfoAsync (/Users/microbit-carlos/workspace/tmp/pxt-error/pxt-microbit/node_modules/pxt-core/built/pxt.js:114007:65)
    at /Users/microbit-carlos/workspace/tmp/pxt-error/pxt-microbit/node_modules/pxt-core/built/pxt.js:114047:39
    at Array.map (<anonymous>)
    at MainPackage.getCompileOptionsAsync (/Users/microbit-carlos/workspace/tmp/pxt-error/pxt-microbit/node_modules/pxt-core/built/pxt.js:114043:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by microbit-carlos** [comment]
I've narrowed this down as working in v7.0.22 and breaking in v7.0.23, which only updated the pxt-core version: https://github.com/microsoft/pxt-microbit/compare/v7.0.22...v7.0.23

So probably something here: https://github.com/microsoft/pxt/compare/v10.2.13...v10.2.14

@riknoll perhaps related to https://github.com/microsoft/pxt/pull/10113 ?
