### ISSUE TITLE
Offline App: Exception on Share with Radio in On Start

### ISSUE THREAD

**Issue by thsparks** [microsoft/pxt-microbit#5965]
I have only seen this happen twice, but occasionally when I share I get a popup with an error:

![image](https://github.com/user-attachments/assets/a80099b2-72a1-4da3-8476-0ef78b852756)

[Window Title]
Error

[Main Instruction]
Unexpected Error

[Content]
An unexpected error has occurred. If this persists, please report it at https://github.com/Microsoft/pxt/issues/new.

Error: unknown command POST screenshot

Error: unknown command POST screenshot
    at throwError (C:\Users\thsparks\AppData\Local\makecode_microbit\app-7.0.45\resources\app\out\src\workspace.js:78:15)
    at Object.handleApiRequestAsync (C:\Users\thsparks\AppData\Local\makecode_microbit\app-7.0.45\resources\app\out\src\workspace.js:73:15)
    at StaticServer.handleRequest (C:\Users\thsparks\AppData\Local\makecode_microbit\app-7.0.45\resources\app\out\src\staticServer.js:119:23)
    at Server.<anonymous> (C:\Users\thsparks\AppData\Local\makecode_microbit\app-7.0.45\resources\app\out\src\staticServer.js:67:64)
    at Server.emit (node:events:513:28)
    at parserOnIncoming (node:_http_server:1072:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)

[OK]

**Comment by thsparks** [comment]
Seems related to having two microbits open in the sim panel. Only repros if you have a "radio send" kind of block in the On Start.
