### ISSUE TITLE
mkc is failing (C++ build failed, Code: 500/???)

### ISSUE THREAD

**Issue by ramseyball** [microsoft/pxt-microbit#5978]
1. git clone https://github.com/tballmsft/microdata
2. cd microdata
3. mkc

```
$ mkc
using project: C:\github\tballmsft\microdata/pxt.json
using config: C:\github\tballmsft\microdata\mkc.json
(node:8360) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
using editor: https://makecode.microbit.org/alpha v7.1.5
Download https://pxt.azureedge.net/compile/270ccb174b8017b40b3e223c8ef841fea049eff9ad4b8c2d7e078d9464aa4887.hex
compiling C++; this can take a while
Download https://www.makecode.com/api/compile/extension
Download https://makecode.com/compile/270ccb174b8017b40b3e223c8ef841fea049eff9ad4b8c2d7e078d9464aa4887.json
build log https://makecode.com/compile/270ccb174b8017b40b3e223c8ef841fea049eff9ad4b8c2d7e078d9464aa4887.log
C++ build failed
Code: 500 / ???
Exception: Error: C++ build failed
    at Ctx.<anonymous> (C:\Users\tball\AppData\Roaming\npm\node_modules\makecode\built\service.js:168:39)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\tball\AppData\Roaming\npm\node_modules\makecode\built\service.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Build failed
```

**Comment by ramseyball** [comment]
Also fails to compile in makecode.microbit.org/beta with the following (which indicates compile service failed to produce a blob):

**Comment by ramseyball** [comment]
Also fails to compile in makecode.microbit.org/beta with the following (which indicates compile service failed to produce a blob):
```
error: pxt_modules/jacdac/mbcompat.ts(18,16): error TS9200: !!proc || !bin.finalPass
error: pxt_modules/jacdac/packet.ts(296,13): error TS9200: !!proc || !bin.finalPass
error: pxt_modules/jacdac/routing.ts(1993,9): error TS9200: !!proc || !bin.finalPass
error: pxt_modules/jacdac/routing.ts(1994,9): error TS9200: !!proc || !bin.finalPass
error: pxt_modules/jacdac/routing.ts(1995,9): error TS9200: !!proc || !bin.finalPass
error: pxt_modules/jacdac/routing.ts(2070,5): error TS9200: !!proc || !bin.finalPass
error: pxt_modules/pxt-arcadeshield/controllerbutton.ts(93,21): error TS9200: !!proc || !bin.finalPass
error: pxt_modules/pxt-arcadeshield/screenhelpers.ts(97,9): error TS9200: !!proc || !bin.finalPass
error: pxt_modules/pxt-arcadeshield/screenhelpers.ts(109,9): error TS9200: !!proc || !bin.finalPass
error: pxt_modules/pxt-arcadeshield/screenhelpers.ts(170,9): error TS9200: !!proc || !bin.finalPass
error: pxt_modules/pxt-arcadeshield/screenhelpers.ts(212,1): error TS9200: !!proc || !bin.finalPass
```

**Comment by abchatra** [comment]
Thanks @ramseyball  for the bug.

**Comment by martinwork** [comment]
Arising from support ticket https://support.microbit.org/helpdesk/tickets/83027 (private)

Here is another example
https://makecode.microbit.org/_X8VEL5dw2TuM

**Comment by abchatra** [comment]
@martinwork this should be fixed. Can you try now?

**Comment by martinwork** [comment]
Still seems the same @abchatra 
![image](https://github.com/user-attachments/assets/dcacecef-30d2-402e-a0d2-8004390f7895)

**Comment by martinwork** [comment]
Looking at the build log, there might be an error in the extension.

**Comment by martinwork** [comment]
After a more.../Reset, it's building as in the incognito window, without going to the compiler.

**Comment by ramseyball** [comment]
Works fine for me now
