### ISSUE TITLE
Attempting to build static copy

### ISSUE THREAD

**Issue by gbaman** [Microsoft/pxt-microbit#665]
So given the internet connection at our Raspberry Jam is a tad unreliable, we have decided the best course of action given we use Makecode for the microbit a decent bit, is to run a copy locally.
So I thought, how hard could it be to build a static copy...

So first thing to say is the docs for setting up an environment for doing so really aren't most clear... 
1. I am attempting to set it all up on Ubuntu 16.04 and started here - https://github.com/Microsoft/pxt-microbit/blob/master/README.md
2. That page links over to the first job being to install the requirements needed for pxt itself here - https://github.com/Microsoft/pxt/blob/master/README.md
3. Which in turn links to here - https://makecode.com/cli
That page only includes dependencies needed for Windows? So I fumbled around and figured out I needed to go install Yotta [using these instructions](http://docs.yottabuild.org/#installing-on-linux), then after getting some errors, discovered I needed to install srecord (with sudo apt-get install srecord) and finally Nodejs.
4. Then next step is installing pxt tool, nice and simple, no problems with that.
5. The next step then isn't hugely clear? I want to run the pxt-microbit target, does this mean I download pxt itself first, then pxt-microbit inside that folder and run ```pxt target microbit```? But then is that actually going and pulling down an npm page for it instead of using the source copy I just downloaded? I eventually just ran ```sudo npm link ../``` to link back up to the pxt folder.
5. At what point to I stop following those docs and switch back to step 1 docs?
6. At this point I do switch back over to the step 1 docs, install everything with ```npm install``` and go ahead and run ```pxt serve```. It hums away and launches a browser, only to be met by the spinning jigsaw piece infinitely sitting there, with the error log below. Same issue as well when running ```pxt staticpkg```.

```
pxt_modules/core/helpers.ts(15,16): error TS2554: Expected 0 arguments, but got 1.

***
*** Build failed: target build failed: Compiler test failed
Error: Compiler test failed
    at Object.userError (/home/andrew/Documents/pxt/built/pxt.js:98337:25)
    at /home/andrew/Documents/pxt/built/pxt.js:130984:19
    at tryCatcher (/home/andrew/Documents/pxt/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/andrew/Documents/pxt/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/andrew/Documents/pxt/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/andrew/Documents/pxt/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/andrew/Documents/pxt/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/andrew/Documents/pxt/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/andrew/Documents/pxt/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/andrew/Documents/pxt/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
***

```

So what is it I am missing? My hoped output is a static copy of the pxt microbit editor that we can run on a bog standard web server locally.

**Comment by abchatra** [comment]
static package is not supported in v0 branch and is supported in v1
